### ISSUE TITLE
Owncloud Plugin

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#131]
Create an roundcube Plugin which allows deeper integration, e.g. Custom theme within roundcube and use OwnCloud address book

**Comment by mckaygerhard** [comment]
i installed the owncloud plugin into the roudncube and installed also the roundcube plguin into the owncloud, so well here have a some redundant plguins functionallity.. so : 

1) when goin iinto roundcube and click on tab owncloud, all session will invalidates..
2) when goin into woncloud and click on tab mail, works well only if do not click owncloud tab or panel are hidden

so the will be good a flag into both plugins that tell to the other that do not enable it or not relogin... or simples do not work due the redundant credentials problem..

**Comment by mckaygerhard** [comment]
hello @hypery2k , i have installed both apps, (in oc, the rc app, and in rc the kolab-oc plugin)..
if both systems have both apps installed the session goes into and loop and both invalidates.. 
so temporally i made in my production server a code when using rc that if a oc session are detected do not show the oc plugin link and do not perform any login for kolab-oc plugin...

i think if u resurge from ground and goes to made a new release 2.6.0 must think about this if use the kolab sources code

**Comment by hypery2k** [comment]
i don't think I'll have time for this, just one more feature to maintain as free beer ;)

**Comment by mckaygerhard** [comment]
well now its not necesary i think, currently the next brand of rc will implement cloud support.. so i guest this issue can be closed due soon rc will have this feature implemented.
