### ISSUE TITLE
Support for kolab

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#132]
Add Support for integrating kolab groupware, see http://www.kolab.org/

**Comment by mckaygerhard** [comment]
the kolab suite now only works with ldap authentication...  i installed the kolab suite but only the rc part with database backend.. and then oc plguin, and works... so then the rc oc plugin, and rc kolab web frondend per see works with normal documentation of the wiki

i cannot test with complete kolab suite due the need of ldap..
