### ISSUE TITLE
Roundcube app does not load RC content into iframe when RC is installed on subdomain

### ISSUE THREAD

**Issue by jdelasko** [hypery2k/owncloud#253]
Got it installed OK on subdomain, but the iframe content doesn't load.

**Comment by mminks** [comment]
@rpsu Your "add_header" directive brings the solution for nginx users. Thanks for that.

**Comment by mckaygerhard** [comment]
i have same problem with lighttpd and hiawata web servers, any have idea of how to solve here?

**Comment by tholu** [comment]
Solution for Apache2: 
```
Header always set X-Frame-Options SAMEORIGIN
```

**Comment by mckaygerhard** [comment]
thanks @tholu for u'r contribution.
