### ISSUE TITLE
avoiding allow_url_fopen

### ISSUE THREAD

**Issue by spali** [hypery2k/owncloud#289]
Thanks for this great integration of roundcube, it fits perfectly my requirements, except using the files from owncloud in roundcube, but there are already issues about that :)
One point I would like to see an improvement:
I had to activate the php option allow_url_fopen to get the roundcube app working as expected.
Don't want to start discussing if this is a good idea or not, but many shared hosting provider do not allow it, and personally I don't like it too because it's usually avoidable.
Maybe you could enhance this (at least for installations on the same url/host)

**Comment by hypery2k** [comment]
now cURL is used, see #312
