### ISSUE TITLE
Integration with 2step Google Verification - Connection Error

### ISSUE THREAD

**Issue by dom-madrid** [hypery2k/owncloud#290]
Great App, but is there a way to get it working with RoundCube and the 2 step authentication plugin ? So far, I only get rejected with the following errors:

Error   roundcube   Not rendering roundcube iframe view due to errors  
Error   roundcube   OC_RoundCube_App.class.php->showMailFrame(): RoundCube can't login to roundcube due to a login exception to roundcube 
Error   roundcube   OC_RoundCube_App.class.php->login(): user@domain.com: RoundCube can't login to roundcube due to a login error to roundcube
##

**Comment by mckaygerhard** [comment]
in the plugin added a white list ip for your network, this permits users login if are inside your network.. by now this are a workaroud solution for that request.. i'll close this issue due there's no interes in this issue that complicates for most simple users the life (users only what to login as their xpected in nomadays)
