### ISSUE TITLE
wrong used space when dbms backend are postgresql, reported as double, in admin no free space

### ISSUE THREAD

**Issue by mckaygerhard** [hypery2k/owncloud#293]
The used space if postgresql are used for oc are reported as double...

currently i cannot find where are the error, due my limitations so by me i cannot solve this issue..

* in admin the query made a group by and reports no free space..
* in normal users, reports double of used space, or reports the max user used space for all oters as same

i'll try to find more, but time for me are gone right now.. for now i test both plugins and rouncube plugin works very well now.. storagecharts hav a bug but was fixed and postgresql now works, .. but with this two problems..

**Comment by mckaygerhard** [comment]
i started the investigation around this, i have very little knowlegd about php and oc but i'll be something to help

**Comment by mckaygerhard** [comment]
#317 marked as related to here..

**Comment by hypery2k** [comment]
fixed

**Comment by mckaygerhard** [comment]
wow! i'll tests with postgres in 4 days, now i'm on the flisol !
