### ISSUE TITLE
Roundcube 1.1-Beta Firefox Bug

### ISSUE THREAD

**Issue by Fmstrat** [hypery2k/owncloud#295]
Jquery reports an error with the latest 1.1-Beta of Roundcube which causes the message list to not display due to the methodology currently employed on fadeOut overlaying the message list.

A fix has been created in this pull request: https://github.com/hypery2k/owncloud/pull/294

**Comment by hypery2k** [comment]
I've added you as collaborator to the GitHub project. Makes things easier to change and you can reuse the Continous Integration job for testing in different environments ...

**Comment by Fmstrat** [comment]
Thanks. I'm not really familiar with owncloud development yet, just starting building some apps myself. Is there documentation on the CI for it? I didn't see it in the developers manual.

**Comment by mckaygerhard** [comment]
close due #294

**Comment by hypery2k** [comment]
the automated tests are still not working with RC1.1 beta ;)
