### ISSUE TITLE
Connection problem to Roundcube server since update Owncloud 7.0.4 and Roundcube 1.0.4

### ISSUE THREAD

**Issue by airasim** [hypery2k/owncloud#297]
Hello hypery2k,

since updating Owncloud to 7.0.4 and Roundcube to 1.0.4 I get the following error when I try to connect to Roundcube via mail-button in Owncloud:
ERROR: Technical problem during trying to connect to roundcube server, Unable to determine network-status due to technical problems.

Owncloud's logging the following:
Error 	roundcube 	Got the following error code: 20 	2015-01-17T13:47:29+00:00
Error 	roundcube 	Not rendering roundcube iframe view due to errors 	2015-01-17T13:47:29+00:00
Error 	roundcube 	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can't login to roundcube due to a network connection exception to roundcube 	2015-01-17T13:47:29+00:00
Error	PHP	fopen(https://xxx.xxx.de/roundcube/) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found at /home/xxx/public_html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php#430

I'm using Firefox 35.0. Owncloud is running on a shared hosting server (Linux 2.6.32-531.17.1.lve1.2.60.el6.x86_64, Apache-Version 2.2.29, PHP-Version 5.3.29, MySQL-Version 5.6.22, Perl-Version 5.10.1).

I didn't look into system-requirements of OC-Roundcube-App before updating, so I now know that my versions are not supported yet...

Thanks in forward
airasim

**Comment by mckaygerhard** [comment]
theres some changes required to handle certificate issues, do u have and own generated or self-signed cert file on u'r server?

**Comment by airasim** [comment]
This could have been the solution, because i had a self signed certificate before I updated to 1.04./ 7.0.4. But since yesterday i have a certfificate from StartCom. Completely deleting the old certificate and even turning off https didn't help. I also importet the intermediate and the authoritiy certificate by StartCom - also didn't help. Before installing  the updates of Owncloud/ Roundcube I didn't have problems with my self signed certificate (disregarding the security warnings from browser).

**Comment by mckaygerhard** [comment]
hey @airasim  please u can try https://github.com/hypery2k/owncloud/wiki/Update-or-removal-tips-of-and-app 

u said that upgrades, so then its not fresh install, i have same problem in my production env..  theres some issues with upgrades , so the please try first https://github.com/hypery2k/owncloud/wiki/Update-or-removal-tips-of-and-app and report feedback...

NOTE: in my production env i cannot upgrade satisfactory from oc 6.0.1 to 6.0.2 and rc 0.9 to 1.0 with this plugin, also with same version of oc and rc, i cannot upgrade the roundcube plugin .. finally i must setup a new fresh install in a perform stop annual maintenance.

**Comment by hypery2k** [comment]
Can you enable debug logging in owncloud and roundcube owncloud plugin? Please post the logs. Also provide more info from which environment you're updated from?

**Comment by hypery2k** [comment]
so far, no issues with the latest build without cron: https://martinreinhardt-online.de/jenkins/job/OwnCloud_integration_tests/

**Comment by airasim** [comment]
i think the problem was, that i connected to owncloud via https://owncloud.mydomain.de/ (which is redirected to https://mydomain.de/owncloud) and rondcoube is stored under https://mydomain.de/roundcube. by using the direct url there is no problem.

**Comment by hypery2k** [comment]
I've updated the wiki for this https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#normal-procedure-setup
