### ISSUE TITLE
roundcube: email identity isnt saved properly

### ISSUE THREAD

**Issue by tristan-k** [hypery2k/owncloud#298]
I'm using ownCloud 7.0.4 (stable) and your roundcube app version 2.5.4.252. Connecting to the roundcube instance is working but the email identity isnt save properly in mysql. I followed the instructions to log in again after setting credentials, but everytime I start the roundcupe app inside owncloud I'll have to login manually. I checked the mysql tables and it seems that the password field for the email identity I entered is empty. Also everytime I came back to settings page in owncloud to check for the email identity, there is just the username of my owncloud user saved. Any suggestions?

**Comment by hypery2k** [comment]
what roundcube version are you using? Can you provide any logs? Go to the admin settings and enable debug logging for owncloud and roundcube and post it here

**Comment by tristan-k** [comment]
I'm using Roundcube Webmail 1.0.3. Here are log files:

```
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:44:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:40:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:36:11+00:00
Error	roundcube	Got the following error code: 10	2015-01-23T20:36:05+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-01-23T20:36:05+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2015-01-23T20:36:05+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2015-01-23T20:36:05+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:36:05+00:00
Error	roundcube	Got the following error code: 10	2015-01-23T20:35:58+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-01-23T20:35:58+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2015-01-23T20:35:58+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2015-01-23T20:35:58+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:35:58+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-01-23T20:35:56+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-01-23T20:31:17+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-01-23T20:30:35+00:00
Error	PHP	Undefined index: password at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php#45	2015-01-23T20:30:35+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-01-23T20:30:26+00:00
Error	PHP	Undefined index: password at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php#45	2015-01-23T20:30:25+00:00
Error	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n URL (url:https://USER.uberspace.de/) open failed.	2015-01-23T20:29:54+00:00
Error	PHP	fopen(https://USER.uberspace.de/): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php#496	2015-01-23T20:29:54+00:00
Error	PHP	Uninitialized string offset: 0 at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php#387	2015-01-23T20:29:54+00:00
Fatal	core	Invalid OCS content returned for app roundcube
```

**Comment by hypery2k** [comment]
are you using autologin? or did you save the user/password within your user settings?

**Comment by tristan-k** [comment]
I tried both ways. First autologin, then saving the email identity. I followed this instructions to make sure that autologin wasn effecting anything:

```
 DELETE FROM owncloud.oc_appconfig WHERE appid="roundcube"; 
 DELETE FROM owncloud.oc_preferences WHERE appid="roundcube"; 
 DROP TABLE owncloud.oc_roundcube;
```

**Comment by hypery2k** [comment]
seems that fopen is not allowed in your setup, [see](http://php.net/manual/de/filesystem.configuration.php#ini.allow-url-fopen)

But you need fopen to be activated. ```allow_url_fopen``` is generally set to On. If it is not On, then you can try two things.

1. Create an .htaccess file and keep it in root folder ( sometimes it may need to place it one step back folder of the root) and paste this code there.
```php_value allow_url_fopen On```

2. Create a php.ini file (for update server php5.ini) and keep it in root folder (sometimes it may need to place it one step back folder of the root) and paste the following code there:
```allow_url_fopen = On;```

Please change your configuration to one of the recommendations above and report back if this solved your problem

**Comment by tristan-k** [comment]
Did that, but now I access owncloud only with through my subdomain owncloud.user.de

Hera are the log files:

```

Debug	roundcube	OC_RoundCube_AuthHelper.class.php: Login error during refresh.exception 'OC_Mail_NetworkingException' with message 'Unable to determine network-status due to technical problems.' in /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php:422 Stack trace: #0 /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php(329): OC_RoundCube_Login->sendRequest('/roundcubemail/') #1 /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php(280): OC_RoundCube_Login->updateLoginStatus() #2 /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeApp.class.php(273): OC_RoundCube_Login->isLoggedIn() #3 /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php(121): OC_RoundCube_App::refresh('owncloud.trista...', '', '/roundcubemail/') #4 [internal function]: OC_RoundCube_AuthHelper::refresh() #5 /var/www/virtual/USER/html/owncloud/lib/private/backgroundjob/legacy/regularjob.php(14): call_user_func(Array) #6 /var/www/virtual/USER/html/owncloud/lib/private/backgroundjob/job.php(36): OC\BackgroundJob\Legacy\RegularJob->run(Array) #7 /var/www/virtual/USER/html/owncloud/cron.php(126): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 {main}	2015-01-25T15:24:26+00:00
Error	PHP	fopen(https://owncloud.USER.de/roundcubemail/): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php#496	2015-01-25T15:24:26+00:00
Debug	roundcube	OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under /roundcubemail/	2015-01-25T15:24:26+00:00
Debug	roundcube	OC_RoundCube_AuthHelper.class.php->refresh(): Preparing refresh for roundcube	2015-01-25T15:24:26+00:00
Error	roundcube	Got the following error code: 20	2015-01-25T15:24:24+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-01-25T15:24:24+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a network connection exception to roundcube	2015-01-25T15:24:24+00:00
Error	PHP	fopen(https://owncloud.USER.de/roundcubemail/): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 at /var/www/virtual/USER/html/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php#496	2015-01-25T15:24:24+00:00
Debug	roundcube	OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under /roundcubemail/	2015-01-25T15:24:24+00:00
Debug	roundcube	tpl.mail.php: Found valid user login data.	2015-01-25T15:24:24+00:00
Info	roundcube	tpl.mail.php: Preparing pre-check before rendering mail view	2015-01-25T15:24:24+00:00
Debug	roundcube	tpl.mail.php: Opening iframe for RC-host owncloud.USER.de with port	2015-01-25T15:24:24+00:00
Debug	roundcube	OC_RoundCube_App.class.php->checkLoginData(): Found login data for USER	2015-01-25T15:24:24+00:00
```

**Comment by hypery2k** [comment]
looks better now, but can you access https://owncloud.USER.de/roundcubemail/ directly? Did that work?
Because the log says that it did not found the URL

**Comment by tristan-k** [comment]
No, I cant reach roundcube at  https://owncloud.USER.de/roundcubemail/. Enabling allow_url_fopen seems to impact a lot of other things. I cant access any services directly anymore, only with subdomains.

**Comment by hypery2k** [comment]
so then enter your complete URL of roundcube within the admin settings, see [wiki](https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage) for more details.
Enabling fopen should not affect subdomains. Did you use the .htaccess method?

**Comment by mckaygerhard** [comment]
i see that complete url setup are not documented in the wiki, i forgott to added in lasted editing.. i edit now.. [[Roundcube-OC-Installation-and-usage#subdomain-troubles]] here https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#subdomain-troubles

**Comment by titansmc** [comment]
Hi @mckaygerhard ,
Thanks for the info, but I still don't understand what you mean by "same browser". 

IMPORTANT: Keep in mind that this only works if owncloud and roundcube are running on the same browser (Same-Origin Policy!)

By the way, I am getting this error (probably this is not the best place to post it, if so, sorry):

"reqId":"14415907e72373e901a74d4966230ef0","remoteAddr":"84.88.53.36","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening url http:\/\/https:\/\/webmail03.bsc.es\/roundcubemail-1.1.1\/ failed with Could not resolve host: https","level":3,"time":"2015-05-20T10:54:02+00:00"}

I believe this is not true, since from owncloud box I can reach webmail03 without any problem. 
My setup is webmail server apart from owncloud server.

Thanks a lot.

**Comment by mckaygerhard** [comment]
umm maybe some typo in the code.. let me try in 6 days and i'll post here..  .. so the i reopen and test.. similar setup.. if i could reproduce or not post any result.. the issue will be closed again..
