### ISSUE TITLE
CSP error on charts

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#305]
Getting
```
Refused to execute inline script because it violates the following Content Security Policy
```
with version 2.5.4 on OC8

**Comment by mckaygerhard** [comment]
hi, please remenber do not drop support for older version of OC.. my job still use oc6 and few oc7 installs

**Comment by hypery2k** [comment]
of course not ;)

**Comment by hypery2k** [comment]
working so far, with OC6, OC7 and OC8 without any CSP errors, just die size unit dropdown is not working, so I removed it within the current version and will add it later
