### ISSUE TITLE
login error starting by second use

### ISSUE THREAD

**Issue by fjies** [hypery2k/owncloud#315]
Hi,

first I installed the roundcube client and app and all is going fine.
After a while I get an error while opening the app in oc.
(Unable to login to roundcube)

If I start a new private browser, the app login automatically.

Is it possible, that there is an error with the cookies?

My system is a oc 7.0.4 instance with working cronjob on ubuntu.

Thanks for that great app, regards

**Comment by hypery2k** [comment]
tell us a little bit about your setup. what app version are you using.
Where is owncloud and roundcube installed on your server? With which URL do you access both services directly and what are you're admin-setting within owncloud?

Do you have any log?

**Comment by mckaygerhard** [comment]
due the tip "i start a new private browser" i intuye that there's some security issues related to newer browsers.. i can confirm that with very older versions of firefox with oc 6, login as expected but in newer instalation oc 7 with newer browsers dont work.. i cannot test oc 7 installations on older versions due donsnt work.. (firefox 4 or iceweasel 3.6.24)

**Comment by mckaygerhard** [comment]
@fjies  do u read the wiki instalation about security contents? there's some setup in the oc and rc u must done

**Comment by fjies** [comment]
I'm running the app version 2.5.4 (newest from app-store)
with oc 7.0.4 and a fresh install of roundcube 1.1.0

The install steps are all done (I think).

For example I use Firefox 34.0.5.

If I startup the computer and open my cloud, I'm automatically logged in and roundcube app does not work. If I relogin it works!

The log only says:
OC_RoundCube_AuthHelper.class.php->refresh(): Finished refresh for roundcube
OC_RoundCube_App.class.php->refresh(): Successfully refreshed the RC session.

What more info can I tell you?

**Comment by mckaygerhard** [comment]
there are extra procedures when custon setups are present, u have custom setup present, do u apply the extra procedures?

**Comment by hypery2k** [comment]
I can reproduce the error with roundcube 1.1.0 and will fix it together with #312

**Comment by mckaygerhard** [comment]
well seem i must take one empty server and install a environment with oc 7 and rc 1.X .. i'v very "deprecated" deploys je je je

**Comment by hypery2k** [comment]
I've setup an docker based dev environment which can be used the easily setup and test environment, see https://github.com/hypery2k/owncloud/wiki/Development-Setup#docker-setup for more details
