### ISSUE TITLE
ERROR: Technical problem during trying to connect to roundcube server, Unable to determine network-status due to technical problems. 

### ISSUE THREAD

**Issue by powerhosting** [hypery2k/owncloud#316]
Dear hypery2k,

I am having trouble following the guide on app.owncloud.com.

I have mostly setup as it was requested just my setup is a bit different.
I have modified so the Virtualhots of apache is pointed to /owncloud so the / is actually the owncloud itself, therefore my domain.com is pointed directly to owncloud.
I have downloaded and extracted the files to /apps/roundcube folder and tried to setup in owncloud but with no luck. The issue might be that the mail server is not set but I am not sure where to set it up. I have an external mail server that uses a separate authentication which I have found in my profile and I did the needful. 
Could you give me advice how to proceed with the troubleshooting? In my logs i found this:

OC_RoundCube_AuthHelper.class.php: Login error during refresh.exception 'OC_Mail_NetworkingException' with message 'Unable to determine network-status due to technical problems.' in /var/www/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php:422 Stack trace: #0 /var/www/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php(329): OC_RoundCube_Login->sendRequest('/apps/roundcube...') #1 /var/www/owncloud/apps/roundcube/lib/RoundCubeLogin.class.php(280): OC_RoundCube_Login->updateLoginStatus() #2 /var/www/owncloud/apps/roundcube/lib/RoundCubeApp.class.php(273): OC_RoundCube_Login->isLoggedIn() #3 /var/www/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php(121): OC_RoundCube_App::refresh('bakosnet.hu', '', '/apps/roundcube...') #4 [internal function]: OC_RoundCube_AuthHelper::refresh(Array) #5 /var/www/owncloud/lib/private/route/router.php(250): call_user_func(Array, Array) #6 /var/www/owncloud/lib/base.php(763): OC\Route\Router->match('/apps/roundcube...') #7 /var/www/owncloud/index.php(36): OC::handleRequest() #8 {main} 

RoundcubeLogin.class.php: sendRequest: \n Network connection failed on fopen(). Please check your path for roundcube with url http://domain.com/apps/roundcube/ on hostdomain.com

**Comment by mckaygerhard** [comment]
do u read the requeriments in the wiki page? or do u read the wiki page here in github?

**Comment by mckaygerhard** [comment]
see in u'r redaction seem that u dont have configure a mail server and rc installed!

so in the wiki section u must read the extra setup steps for custom installations.. 

do u have the roundcube in the same server, or the mail system have already the rouncube web interface?

please details u'r setup for better support.. lest see how can made.

**Comment by mckaygerhard** [comment]
and closing until user @powerhosting answer.. seems that assume that this app use the mail setup from oc and app have already and mail web interface embebed.

**Comment by powerhosting** [comment]
Dear mckaygerhard,
I have the special version from app.owncloud.com and i have set it up on the same server as owncloud however my mail server is running on a separete host therefore this might be causing the issue however I managed to install rainloop without any issues since it lets me edit mail server / domain there I managed to setup correctly. Thanks for the help anyway.
Best regards,

**Comment by mckaygerhard** [comment]
hello @powerhosting , this app its not for rainlood, u must have installed roundcube in any other or same host , no care if mailserver are in other host..

if oc are installed in root of apache this are not the problem.. the problem its that know nothing of your configuration mail service..

in the wiki, requeriments u note that need a mailsers (in u'r case in ahoter host, good)
also a mail web interface, roundcube (here u does not post any about that)
and also setup the app with the configured web mail interface..

u'r setup of mail server (the software of service itself) does nothing related to the app, the more related are the web ui of the mail service, in this case roundcube!

please post u'r setup of roundcube, the setup of oc and p'hp version (as must be done in each reported issue) and we will help to u.

**Comment by mckaygerhard** [comment]
i forgot, @powerhosting , i mean when i said "roundcube" it refers to the web mail interface and not to this app name.. 

the app name "roundcube" its only a bridge to use the real roundcube web mail interface, u must read carefully the wiki in this github.
