### ISSUE TITLE
App shows same space for all users

### ISSUE THREAD

**Issue by muenchhausende** [hypery2k/owncloud#317]
The Plugin shows the same space for all users. 

Im using OC8.0.2 stable

I installed Storage Charts APP, following the Instructions. I then enabled the app as ADMIN and under charts it showed the correct stats for the admin user. 

After that i logged in as another user with no files and it showed the same space used for him and added it to the used space for all users Pie. 

I then tried it with different users and it always showed the same used space as my ADMIN account an even added the space to the all users charts.

**Comment by mckaygerhard** [comment]
please, its firts install? do u xperience this before or only with lasted release of sc?

**Comment by muenchhausende** [comment]
I recently upgraded my OC- Server from Version 7.x  to 8 and then to 8.0.2. It's the first time that I installed the Storage Charts plugin because it was not necessary before.

**Comment by hypery2k** [comment]
fixed

**Comment by mckaygerhard** [comment]
for historycally used only, see #321
