### ISSUE TITLE
Display user name 

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#318]
Use display name instead of id, e.g for LDAP

**Comment by thomas955** [comment]
Hey,

Thanks for your work. 
Is it possible to choos what i want to display as username? In my case i need id (uid from ldap) cause i have some very old users from owncloud 3 and before that still use id as display name.
(Especially in admin section which is most important for me, i want to see the short uids e.g. NThomas or somethink like this).
Thank you in advance.
Thomas

p.s. owncloud 8.1 apache2 php 5.6 mysql 5.6

**Comment by mckaygerhard** [comment]
ummm an update qeury when cahnge the id could be more easy jejejej

**Comment by hypery2k** [comment]
Adding support for displaying both display name and userid:
![owncloud](https://cloud.githubusercontent.com/assets/979121/9142343/5c77c350-3d3f-11e5-979d-e3e153e65079.png)

**Comment by mckaygerhard** [comment]
hi with this commit now storagecharts2 have a limit of a thousand of users due the array parsing result of the list of users in the code..

i wish to know how to made this configuration a option, i can made some code lines for that in few mounts (right now i'm busy)

i mean does not used the array build list, due in my company theres a load of 3000 users and in firts tests php hangs and nerver restusns a response if any admin user are logged and try to view the chart (i know that due the array, it happened to me in the selectra software)

**Comment by hypery2k** [comment]
I've created an issue for this, see #350 

Besides that a snapshot build is available at: https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/332/

**Comment by mckaygerhard** [comment]
i see the commint in firts lines..

that's better if array user list fail so then get to old behabior! but still the array list the php engine still try to fill with lot of users, so the thousands of userss will fit in a php array capability?

i not tested this part yet with my 3000+ users production environment.. 'ill report later a feedback!

similar behabior i got with selectra software.. i doub work, but lest try and i'll post in #318 !
