### ISSUE TITLE
Share2Share Owncloud

### ISSUE THREAD

**Issue by diablotin84** [hypery2k/owncloud#320]
Hello,

I have a bug with Share2Share Server Owncloud in 8
When I share a folder between 2 Server Owncloud and i upload a file on the folder share on the second server, i have this error:

Upload failed. Could not get file info.

And in the log, on the first server:

{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/readonlycache.php#16","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: fileid at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#99","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"887a8b699626e909e9fe9e78da6b001e","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: etag at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#127","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/readonlycache.php#16","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: fileid at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#99","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"bcf76e3b72199ccc1cd4fd891a307301","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: etag at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#127","level":3,"time":"2015-03-25T13:35:26+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/readonlycache.php#16","level":3,"time":"2015-03-25T13:35:27+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-03-25T13:35:27+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:27+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: fileid at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#99","level":3,"time":"2015-03-25T13:35:27+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#106","level":3,"time":"2015-03-25T13:35:27+00:00"}
{"reqId":"abbbc902c699872430ea41552c686521","remoteAddr":"MY_IP","app":"PHP","message":"Undefined index: etag at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#127","level":3,"time":"2015-03-25T13:35:27+00:00"}

Any idea ?
Thks for help.

**Comment by mckaygerhard** [comment]
hi, u must report agains the oc repo, this its a specific oc app repo. see README and the intro of the main index...
