### ISSUE TITLE
Wrong space calculation

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#321]
I just installed this on ownCloud 8.0.2 (Ubuntu Server 14.04.2 LTS) and although it does not break, it does not actually work. It gives false information which is actually worse.

I have 4 admin accounts all with various amounts of data in them ranging from 2 MB to 32 MB with a 1GB limit. The system has over 1GB of free space.

I login as the admin account and it although it shows "All Users" in the ratio pie chart, it only shows the admin account taking up 3.62% of the total chart and free space of 96.38%. This account is using 2.4MB. That is actually 0.0024% of just that 1 users limit/account. If we were to add all users together manually, I have 39.3MB which is still only 0.039% of 1GB. No idea where its getting these numbers.

It does not register any of the space used by the other users even though it sees the other user names.

As I login to each account, it seems to start adding/registering that user's space in the list...but after going through all of them, they all report using the exact same incorrect percentage of 3.62%

see https://apps.owncloud.com/content/show.php/Storage+Charts+2?content=165528

**Comment by mckaygerhard** [comment]
hello @hypery2k this already posted by me after the issue around portability of the query?

**Comment by Worst45** [comment]
Hello,
I still have the same problem with OwnCloud 8.0.4 and latest storagecharts2 version taken from github. It only populate database with users that logged to the web interface, with false values.

cd /data/owncloud/data
du -sh *
26M     user.1
620K    user.2
320M    user.3
783M    user.4
600K    user.5

df -h /data
Filesystem         Size      Used Avail  %  Mount
/dev/sdb1           35G    1,2G   32G   4% /data

mysql -B -e 'SELECT * FROM owncloud.oc_storagecharts2'
stc_id  oc_uid  stc_month       stc_dayts       stc_used        stc_total
28      user.4 201506  1433980800      1184369429      34908191509
29      user.2  201506  1433980800      1184369429      34908191509

For the plugin, users 2 and 4 each store 1.1 GB... but on filesystem they only have 620 KB and 783 MB

**Comment by hypery2k** [comment]
currently having not much time for investigated on this issue

**Comment by mckaygerhard** [comment]
theres some way to take the "du" command and parse to the oc code? this solve the problem.. due du are very exact!

**Comment by Worst45** [comment]
I started to debug myself app.php.

$datadir = OC_Config::getValue('datadirectory');
returns the global data directory, not the one use by the current user... 

Appending the user id does the trick:
$datadir = OC_Config::getValue('datadirectory').'/'.OCP\User::getUser();

Is it an API change from Owncloud since 8.0.2?

And just another though, why only calculate space for current user, and not parse all users with OCP\User::getUsers()? It would prevent bug of charts only showing logged in users. You just need to add an optional extra parameter to OC_DLStCharts::update() to force user id updated

**Comment by hypery2k** [comment]
thanks for your suggestions. I just currently don't have time for this. I've a regulary job and just don't have free time for this currently. So feel free to make a pull request

**Comment by mckaygerhard** [comment]
i'll make a pull request and test by myseflt.. using the info that @Worst45 provide it

**Comment by mckaygerhard** [comment]
hi @hypery2k and @Worst45 , i tested the trick and tri something others, this code works only for normal users... and works poerfectly,, still i have to found how to fix the display for admin users, admin users must display all users space used...

due i found that code work perfectly (almost for normal users) i'll commit that change and now fixed some logged errors in storage charts that confuse me when i debugged the rounducbe app...

**Comment by Worst45** [comment]
Hi @mckaygerhard, for available space seen by users I think the better method (to my mind) would be:
 - "admin" group see all available space,
 - other people are impacted by quota usage (illimited / fixed). Illimited = see all available space. Fixed = consider that quota limit is the maximum size.

**Comment by mckaygerhard** [comment]
the firts u said are already fixed.. when users registered and use their account, the table of the storage will be fit in the time.. and the chart will be upgraded for admin users...

the other, i'm certified that couta usage are good, ill commit the changes and fixed that problem..

theres some issues with admin charts .. i'm thinking for admin must have a conditional that detct if users are normal (and then parse the user part that u said  @Worst45 ) and if are admin does not parse the user part
