### ISSUE TITLE
Manual roundcube details not saved

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/owncloud#324]
manual user settings seems to be not saved when autologin is disabled:
![webmail_-_owncloud](https://cloud.githubusercontent.com/assets/979121/7016756/370ce5f0-dceb-11e4-906d-c175fedcfc12.png)

**Comment by hypery2k** [comment]
maybe related to #300

**Comment by rotdrop** [comment]
Ok, on my side I cannot tell about auto-login, but everything else is now working as before (including changing the email password). One has to logout and log into Owncloud again in order for changes to take effect.

**Comment by mckaygerhard** [comment]
hey @rotdrop please can u post u'r setup again in this issue for easy follo of the problem..

i must tests again , this time in production env.. lasted tests (oc 6 or 7 with rc 1.0rc and 1.0.1) the plguin does not work when i added a lot of plguins into the roundube web mail.. without the enabled plguins additions works well in clean installed env...

**Comment by rotdrop** [comment]
Setup is OC7 or OC8 with RC 1.0.2. I did not add any plugins to the Roundcube web-mailer, except for "archive" and "zipdownload" which seem to be enabled by default.

I'm not using the "auto-login" feature of the OC-app, as my email credentials are completely different from my OC login settings. The email-backend is an IMAP server with SSL and an SMTP server with STARTTLS.

At the moment the master-branch of the OC-Roundcube-app works on my test setup @home, an older version (before the bunch of 2015 changes) runs in a production environment (admin web-portal for our orchestra).

Of course, you did check that your Roundcube web-mail works stand-alone with "a lot of plugins"?

Cheers,
Claus

**Comment by mckaygerhard** [comment]
thanks @rotdrop u make me to save time with that tests..  my current production setup ist close similar... but oc 6 and oc7.

yes my mail interface works very very perfect with the "lot of" plugins, of course i must hack some due many jquery conflicts, specialy for the context menu plguin. but that configurations does not work if enabled the oc plugin.. but when i setup a "clean" env works (before lasted changes) until i enable more plugins (not only one in particular, some mixeds)

**Comment by rotdrop** [comment]
If the underlying web-server is NGINX then it could be that you are running out of "header memory". NGINX reserves only 4k for all that header stuff (HTTP headers, meaning cookies and the like). It's unlikely, though, and could only be the source of the trouble if your RC plugins fill up the HTTP request header with lots of cookies or similar things.

**Comment by hypery2k** [comment]
it's an code error, I've found the error and will commit the fix. I think this is also related to #314, because the user data was saved twice

**Comment by mckaygerhard** [comment]
i'm not revised deeply the code.. of course note some times fails rarely.. but in general case the times when work was when installation was clean adn without plugins.. currently i'm too busy triying to implement a solution alternate to some mocosoft tools.. that's was i'm not deeply here

**Comment by hypery2k** [comment]
no problem. It's an code error, because the private key cannot be read as posted in #314

```
{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"PHP","message":"openssl_private_decrypt(): key parameter is not a valid private key at \/var\/www\/owncloud\/apps\/roundcube\/lib\/RoundCubeApp.class.php#199","level":3,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Starting decryption.","level":0,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->login(): Used roundcube user: ","level":0,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finishe with errors.","level":3,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"PHP","message":"openssl_private_decrypt(): key parameter is not a valid private key at \/var\/www\/owncloud\/apps\/roundcube\/lib\/RoundCubeApp.class.php#199","level":3,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Starting decryption.","level":0,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},{"reqId":"653307bb984ff89451969ce05a0a9d14","remoteAddr":"10.0.2.2","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->login(): Used private key: ","level":0,"time":"2015-04-09T03:53:43+00:00","method":"POST","url":"\/owncloud\/"},
```

**Comment by hypery2k** [comment]
tests with manual login are working so far: https://martinreinhardt-online.de/jenkins/view/BMP_OwnCloud/job/OwnCloud_test/1256/

will need to verify the setup with different environments, see https://martinreinhardt-online.de/jenkins/job/OwnCloud_integration_tests/

**Comment by mckaygerhard** [comment]
as i posted in auto case, in both cases does not save the settings: i query db (postgres) and see use and pass are empty :

1,'systemas','''',''''
2,'general','''',''''

i have two users, both have "''" in table for user and password!

may i help in ahoter thing?

**Comment by hypery2k** [comment]
which version of roundcube app are you tried? I've tested the latest version (https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/291/) with OC7 and OC8

**Comment by mckaygerhard** [comment]
i used (as posted in autologin isue) oc 7.0.4 with rc 1.0.1 also in another (production) oc 6.0.2 with rc 1.0rc1, in both cases the problem are same, user name and passwd never sotred in database table oc_rouncube.. only empty strings... 

in mail render, when invoke $mail_userdata['oc_user'] = OCP\USer::getUser() seem does not retrieve any value.. so i suspect the problem its in someother part but i dont understand still the work of storing the user data in table

**Comment by mckaygerhard** [comment]
i'l tested in production  with postgres and paste here feedback.. thanks
