### ISSUE TITLE
postLogin hook gets executed even when app is not activated for specific user

### ISSUE THREAD

**Issue by skywalker666** [hypery2k/owncloud#326]
When the app is enabled only for certain groups, the post_login hook still gets executed for all users. I have a user group with imap logins, which I enabled the app for. This works as expected with autologin. All other users get a short delay, while the autologin to roundcube fails. Adding OCP\App::checkAppEnabled('roundcube'); to the top of OC_RoundCube_AuthHelper::login() helps. Don't know if that's a limitation of owncloud, but app.php (where the hooks are registered) gets executed on every request.

**Comment by skywalker666** [comment]
Just noticed, if the admin user is not in that certain groups, he can't configure the app anymore. That's probably expected.

**Comment by hypery2k** [comment]
I'm on vacation. Will try to check it in 2 weeks
