### ISSUE TITLE
Multiple Users Wrong Distribution / Not Showing Other users Data: Only Names - Storage Charts 2 Application 2.6.0

### ISSUE THREAD

**Issue by t2tbr** [hypery2k/owncloud#327]
I have only 2 users in my OC 8.03.
My user is an admin, and the other is not.

When I open the graphs, they only display data as if the admin user has all the data. If I open it as the other user, it shows as if only the other user has all the data.

Even if I filter (in the admin page), the other user (clicking in over the other user) it shows 0, just flat lines with value 0.

My setup is with MySql.

---

Quick update: I logged with the other user (it has never been logged before, only Client Sync) and now the charts are displayed as if each user is using 50% of the used space. Example: 21% and 21%, even though I know that that is not correct (should be 80% 20%).

Again, It's showing 50% 50% just because even for the non admin user it's considering the data for all users.

So, User A: 70GB, B:10GB.

Graph for user A (admin): A 80gb, B80gb

Graph for user B: B (80gb)

**Comment by hypery2k** [comment]
I'm on vacation. Will try to check it in 2 weeks

**Comment by mckaygerhard** [comment]
fixed with commit b25494f  please see #321

**Comment by hypery2k** [comment]
@t2tbr Can you retest the latest build: https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/lastSuccessfulBuild/artifact/storagecharts2/target/

**Comment by t2tbr** [comment]
Well, just upgraded to 8.04 and also installed your latest build.
The graphs "Daily Used..." and "Monthly Used..." are working perfectly, but the "Current Ratio free..." graph is not ok.
It displays Multiple users, repeating the name, for instance, User A appears 9 times, with percentages that vary from 6% to 8%, the user B appears 6 times, with percentages within the same range. 

Is it possible that I need to re-build the tables? Should I wait another day to see how things go?

(tomorrow I will post again if the "current" graph changes).

Thanks.
Thiago

**Comment by mckaygerhard** [comment]
please can u made a new build with lasted commit, i put a query with group fixes..

**Comment by mckaygerhard** [comment]
the problem its the subquery, the query now has a prolem, the previous works only in mysql, but in sqlite and postgres fail, i commit a new query, this does not work for daily chart, due group standar sql clause, the problem about that its in the issue  #336 so i close that and all related to "Current Ratio free... graph is not ok." are now in the #336
