### ISSUE TITLE
Top Bar Hidden

### ISSUE THREAD

**Issue by wato1987** [hypery2k/owncloud#328]
Hi, 
love your pluging works very well.
i wonder if you can point me in the right direction, 
i need the small top bar to be shown, as this has a drop down section to allow me to change imap accounts in roundcube.
<div id="topline" role="banner" aria-labelledby="aria-label-topnav"> 

How can i get this to be displayed?

Happy to sus it my self if you can point me in the right direction 

i was guessing its triggering the 'minimal' toggle somewhere?

wato

**Comment by mckaygerhard** [comment]
for that kind of question its better to use the glitter chat of github:

https://gitter.im/hypery2k/owncloud

umm see the wiki https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#usage-and-some-tips-for-issues i think u want to enable the bar show.. 

if there's no such information u expected.. post again feedback
