### ISSUE TITLE
Roundcube invalide private key

### ISSUE THREAD

**Issue by fleixi** [hypery2k/owncloud#330]
Im getting this errorlog:

{"app":"PHP","message":"openssl_pkey_export(): cannot get key from parameter 1 at \/usr\/share\/owncloud\/git\/roundcube\/roundcube\/src\/main\/php\/lib\/RoundCubeApp.class.php#203","level":3,"time":"2015-05-26T17:54:39+00:00"}
{"app":"PHP","message":"openssl_private_decrypt(): key parameter is not a valid private key at \/usr\/share\/owncloud\/git\/roundcube\/roundcube\/src\/main\/php\/lib\/RoundCubeApp.class.php#243","level":3,"time":"2015-05-26T17:54:39+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.","level":3,"time":"2015-05-26T17:54:39+00:00"}
{"app":"PHP","message":"openssl_private_decrypt(): key parameter is not a valid private key at \/usr\/share\/owncloud\/git\/roundcube\/roundcube\/src\/main\/php\/lib\/RoundCubeApp.class.php#243","level":3,"time":"2015-05-26T17:54:39+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.","level":3,"time":"2015-05-26T17:54:39+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube","level":3,"time":"2015-05-26T17:54:40+00:00"}
{"app":"roundcube","message":"tpl.mail.php: Preparing pre-check before rendering mail view ","level":1,"time":"2015-05-26T17:54:45+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.","level":1,"time":"2015-05-26T17:54:45+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->showMailFrame(): There were login errors","level":3,"time":"2015-05-26T17:54:45+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube","level":3,"time":"2015-05-26T17:54:45+00:00"}
{"app":"roundcube","message":"Not rendering roundcube iframe view due to errors","level":3,"time":"2015-05-26T17:54:45+00:00"}
{"app":"roundcube","message":"Got the following error code: 10","level":3,"time":"2015-05-26T17:54:45+00:00"}

Serverconfigure:

Owncloud = owncloud.foo.bar (Version 7.0.4)
Roundcube = www.foo.bar/mail (Version 1.1.0)
Browser = Firefox 38 Ubuntu 15.04

no Autologin

**Comment by mckaygerhard** [comment]
you said have no autolign and diffrerent url's for apps.. do u follow the wiki installation procedure?

**Comment by fleixi** [comment]
Im followed the wiki on this git repo and everything is reachable over owncloud.foo.bar without roundcube itself. Roundcube is settlet in www.foo.bar/mail.

Maybe important: each site have an other selfsight zertificat.

**Comment by mckaygerhard** [comment]
umm u'r problem its related to different sites, in the wiki of roundcube app there's a section about configure special cases, please follow instructions here:

https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#custom-different-server-setup-tips

and take in consideration read the requeriments wiki also...

**Comment by fleixi** [comment]
i have had followed the normal setup because in step 3 after the picture you saying "If you're accessing owncloud via https://owncloud.domain.net and roundcube mail at https://domain.net/mail then enter https://domain.net/mail as full url." and thats my configuration.

I have linked my roundcube to owncloud.foo.bar/mail too and now its working. So fixed with a workaround. thx
