### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by sedrubal** [hypery2k/owncloud#331]
All owncloud app logos are light gray, only the logo of `usage` is black.

**Comment by mckaygerhard** [comment]
please can u pst a image describing the issue... i'm not sure what are taking about..

**Comment by sedrubal** [comment]
sorry... here it is
![usage](https://cloud.githubusercontent.com/assets/5571650/7866414/930238f4-056f-11e5-8bb3-195ff02863c0.png)

**Comment by mckaygerhard** [comment]
ok, this its a minor feature request, if u can make a better logo send me and i'll pust to master

**Comment by sedrubal** [comment]
Now it looks like this: :smile: 

![usage](https://cloud.githubusercontent.com/assets/5571650/7926142/612fd04a-08ce-11e5-8788-550303cc6428.png)

**Comment by mckaygerhard** [comment]
closed by mergin #332 thanks
