### ISSUE TITLE
disable also SSL host verification

### ISSUE THREAD

**Issue by mhus** [hypery2k/owncloud#337]
SSL Host verification should also be disabled if the checkbox ' Disable SSL verification, e.g. for self-signed certificates ' is enabled.

Add the line 'curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);' in RoundCubeLogin.class.php

            if ($this->sslVerifyDisabled) {
                $this->addDebug("openUrlConnection", "Disabling SSL verification.");
                curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
            }

**Comment by hypery2k** [comment]
thanks!
