### ISSUE TITLE
Doubled config for 'information bar' and missing config for 'header navigation menu' in advanced settings

### ISSUE THREAD

**Issue by blue-bean** [hypery2k/owncloud#339]
server version: Synology DSM 5.1-5055 (Apache 2.2.29)
used browser: Firefox ESR 31.7
used own cloud version: owncloud 8.0.4
used app version: 2.6.0-318

Issue:
In the .../owncloud/apps/roundcube/templates/tpl.adminSettings.php the lines 26-31 are doubled in the lines 47-52. So you have twice the config for "Remove information bar on top of page " in the advanced settings.
Instead of that the config for "Remove RoundCube header navigation menu items" is missing in the advanced settings. So lines 47-52 should be replaced with:

		<br>
		<input type="checkbox" name="removeHeaderNav" id="removeHeaderNav"
		<?php if ($_['removeHeaderNav']) echo ' checked'; ?>>
		<label
			title="<?php echo $l -> t('Removes the buttons for different sections (mail, adressbook, settings) within the RoundCube mail application'); ?>"
			for="removeHeaderNav"><?php echo $l -> t('Remove RoundCube header navigation menu items'); ?>
		</label>

**Comment by hypery2k** [comment]
thank you for the hint. Would be great to sent a patch or a pull request next time ;)

**Comment by blue-bean** [comment]
Da ich bisher das Git nicht geclont habe, dieses Mal noch so ;)
