### ISSUE TITLE
Loginprobleme in owncloud

### ISSUE THREAD

**Issue by otti24** [hypery2k/owncloud#340]
Ich habe die oft erwähnten Loginprobleme auch und wenn ich die angebliche 2.6.0 Version auf owncloud.com downloade dann ist es wohl doch die 2.5.4 laut Appinfo.

wo kann ich die richtige Version herbekommen?

**Comment by mckaygerhard** [comment]
i have limited understand of deustland... i recomended when post mus be in english, and search if u'r problem are already reported..

login problems must be detailed, this issue does not detail those "multiple problems" (erwähnten Loginprobleme auch)

Bitte melden Sie spezifische Probleme (wenn du Probleme jedes pro issue und mit Debug-Protokolle Details)
Please report specific problems (if u have problems details each one in a issue and with debug logs)

Maybe u must read the login related issues:
Vielleicht müssen Sie diejenigen im Zusammenhang zu lesen:

 #338, #333 and #316

**For downloading u must READ! (yes again read) the README.md of this repo when said that lasted buiklds are in yenkins with a proper link! Remenber that in unix world always must read firts**
