### ISSUE TITLE
Loginprobleme in owncloud

### ISSUE THREAD

**Issue by otti24** [hypery2k/owncloud#341]
Ich habe die oft erwähnten Loginprobleme auch wenn ich versuche die Logindaten einzugeben steht dort ewig "Saving..." aber es tut sich nix und wenn ich die 2.6.0 Version auf owncloud.com downloade dann ist es wohl doch die 2.5.4 laut Appinfo. 

Wo kann ich die richtige Version herbekommen?

**Comment by mckaygerhard** [comment]
closed as duplicate of #340 please when reporting take carefully of the submit (comment) button

**Comment by hypery2k** [comment]
you'll find the correct version here: https://apps.owncloud.com/content/show.php/roundcube?content=151523

Scroll down and you see this:

![roundcube_apps_owncloud_com](https://cloud.githubusercontent.com/assets/979121/8286163/59b48e74-1908-11e5-9444-cb472d2b2e5d.png)


Just unzip the archive and move it to the server. I have no idea why the store within owncloud is not refreshing with newer versions from apps.owncloud.org
