### ISSUE TITLE
App doesn't work with OC 8.1 [$15]

### ISSUE THREAD

**Issue by alex42ka** [hypery2k/owncloud#344]
Worked perfectly before the update but afterwards I'm now getting a blank screen.

Tried as well versions 2.5.4 and 2.6.0. Both didn't work.

Using Ubuntu 14.04 and Apache.

**Comment by alex42ka** [comment]
I get this in my apache error.log:

```
[Tue Jul 07 19:14:52.499755 2015] [:error] [pid 7102] [client 109.90.233.215:39834] PHP Fatal error:  Class 'OC_Request' not found in /var/www/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php on line 129, referer: https://scroom.de/owncloud/index.php/apps/files/
```

**Comment by mckaygerhard** [comment]
Please, post the php version and the rc version in use, also the setup (internal domian, local instalation, external domains, separate domains etc)

**Comment by alex42ka** [comment]
For me it is the following php version:
```
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Roundcube version: 1.1.1

Both OC and RC are installed on the same server (same domain as well). Users are managed via LDAP, so that they are using the same passwords for OC and RC.

**Comment by mckaygerhard** [comment]
hi @hypery2k i really wish to thanks that u still support in every commit older releases of owncloud.. i noted the conditional around version of oc 8.1 ..

**Comment by Fmstrat** [comment]
@hypery2k I would like to request this get expedited independently of the other bugs and enhancements in the 2.6.1 milestone. The OC_Request error breaks API utilization for other 3rd party apps, and has caused a flurry of bug reports that took me a while to track down that all users had the Roundcube plugin enabled. As an example, if a user has ownNote enabled (for transparency, this is one of mine) and tries to access notes from an Android device through the API, this bug in the Roundcube plugin keeps the ownCloud API from functioning, thus breaking ownNote as well.

**Comment by hypery2k** [comment]
That's funny: This all seems like a lack in design in owncloud. A 3rd party app can break the whole platform. It's really a hassle to get around all this stuff. Making big changes in a non-major version which breaks other stuff. That's the reason I wouldn't like to support anymore my apps. Most people think about OSS are free of cost and the developer should get around all the stuff in the free time...

Besides that I've already provided a fix for the issue.

I think with releasing this bugfix version I will quit development of my owncloud apps...

**Comment by alex42ka** [comment]
Would be sad! You've written a really fine piece of software! But you are right:
There are many people who are not willing to pay for Free Software. I hope that you can find back motivation to work on your apps even in your spare time!
Just one question: Do I have to make git copy of master to get the fixes?

**Comment by mckaygerhard** [comment]
taaking this as reference i really angry with the bounty system of github, the rewards are for reporters event for manpowers and reportes choice if want to donate...

**Comment by Fmstrat** [comment]
@hypery2k I totally agree on the major/minor comment, as I'm in the same boat with the CSP changes removing image support from one of my apps without realizing it. There is actually a discussion going on in the devel mailing list that I started about better ways to keep app developers informed of changes that would break 3rd party apps. Hopefully they adopt an easy method.

On another note, I hope you don't quit developing, the community here is very thankful for your work.

**Comment by LukasReschke** [comment]
Generally speaking: OC_ APIs are _not_ public APIs and can disappear at any time. Please always use OCP ones. If there is no OCP replacement: file an issue.

That said you can also add some version checks to appinfo.xml to define a top version. This way you can ensure that no user is using an unsupported app version on a newer core version. Check the activity app's appinfo for this for example.

**Comment by hypery2k** [comment]
@alex42ka You can download it here: https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/328/

**Comment by mckaygerhard** [comment]
@LukasReschke No one human being who prefers stability and functionality, liked changes, changes like to the zealot tech people or freakys.. so i ask now, woncloud are made for freakys or for funtionall usage... 

in my job still are using oc 5 and oc 6 due are working perfectly, and the open source permits to us make adaptations to make it work in those legacy versions

but of course owncloud are made by an enterprise and a bussines its always change everiting to force upgrades right?

**Comment by RealRancor** [comment]
@Fmstrat @hypery2k 

FYI, oC 8.1 is not a minor but a major version.

**Comment by hypery2k** [comment]
Good to know. Would be better to get informed before the release and not after...

But would be to much work beside inviting every developer to speak at a conference...

**Comment by RealRancor** [comment]
@hypery2k The blogpost was written in March 11, 2015, oC 8.1 was released one week ago.

The announcement about the version change at the developers mailinglist was even early, on Nov 21, 2014:

http://owncloud.10557.n7.nabble.com/release-schedule-and-versioning-changes-td13524.html

**Comment by Fmstrat** [comment]
@hypery2k On a good note, after discussions in the developer mailing list, a blog entry was created by the core developers: https://owncloud.org/blog/owncloud-8-1-brings-massively-improved-api-for-developers/

There is only a quick hit on CSP changes, but it's a good first step. My hope is it will form a habit of pre-release posts on things that will impact app developers.

Thanks.
