### ISSUE TITLE
wrong package

### ISSUE THREAD

**Issue by bone4** [hypery2k/owncloud#345]
On this site
https://apps.owncloud.com/content/show.php/roundcube?content=151523
it is possible to download a package with the name 151523-roundcube_v2.6.1_build429.zip.

But if you have a look on roundcube/appinfo/version you can see: 2.5.4.
This is a old version where I have login problems.

Can you give me please the right package with the content of 2.6.1?

**Comment by bone4** [comment]
My login problem still exists. Roundcube says that the session is expired. I found this:

Solution: set $rcmail_config['ip_check'] = false; in the round cube config file main.inc.php

but I can't find the main.inc.php file.
Can you help me please?

**Comment by mckaygerhard** [comment]
The firts, i noted that.. the mistake are in https://github.com/hypery2k/owncloud/blob/master/roundcube/src/main/php/appinfo/version  .... but i wan to research the proper way to avoid this king of problems with multiple files that defined version info..

then ask to main developer and author about what are thinking respect that..


About the second.. u must see if there's a already opened ticket with the same problem (there's one with a problem with autologin).. if the problem are different open a new ticket and always paste the log, the info of the environment and all neeed other info for provide some help..
