### ISSUE TITLE
Massive slowdowns when enabling Storage Charts 2

### ISSUE THREAD

**Issue by oparoz** [hypery2k/owncloud#347]
### Env

8.0.5
PHP 5.5
FreeBSD

### Problem

At first I thought it was just because ownCloud 8.0 was much slower than 8.1, but when looking at the logs, I started to see lots of "Calculating available space in oc << 8 for client" messages in the logs (in debug mode).
I disabled the app and saw a very substantial change in the speed at which Gallery (per example) was throwing thumbnails at the screen.

Is this a known side-effect?

Also, I get tons of
"Only variables should be passed by reference at apps\/storagecharts2\/appinfo\/app.php#46"

**Comment by mckaygerhard** [comment]
that message appears when client try to call a not defined function on the server.. 

the code are:

```
 if (method_exists($fs, 'free_space')) {
        OCP\Util::writeLog('storagecharts2', 'Calculating available space in oc << 8 for client', OCP\Util::DEBUG);
         $total = OC_DLStCharts::getTotalDataSize($data_dir) + $fs->free_space();
         OC_DLStCharts::update($used, $total);
     }
```

@hypery2k  I put that message for log because I suspected something about why this function did not exist or because if there was.. where the method existe, the oc 8.X slowdown very in performance..

i noted that the free space for admin used are calculated respect the total usage.. not real space available...

seems that u'r oc 8.X have that funtion and its suppost to not

**Comment by oparoz** [comment]
OK, maybe this is an OS thing then. I'm on FreeBSD.

**Comment by mckaygerhard** [comment]
umm i interesting in some info:
1) what fs are u used for the location of "data" directory
2) freeBSD kernel version
3) numbers of users log in when slowdown occurs
4) (assuming this occurs when u used the oc qt client ) version of the oc desktop client
5) complete clean output of debug (if possible and the steps when occurs)
give to me the possible info u can paste

**Comment by oparoz** [comment]
1) ZFS
2) 9.3
3) 1
4) Only noticed when using the Gallery app as it streams lots of files quickly
5) I'll try to give you something asap

**Comment by mckaygerhard** [comment]
hey! do u mean that occurs when using the web interface? not the qt client! ja ja that's new!

ok, so then the call $fs->free_space() have a problem in that particular case.. ummm i cannot said that its a bug of storagechars2 due the proble seems are when a lot of files are in a particular fs, so i think i must waith if a similar issue are reported..

**Comment by lilarcor** [comment]
I have the same situation on oc8.1 when I use web interface

**Comment by oparoz** [comment]
@mckaygerhard - Good point about the logs. I'll try again without the debug mode to see if it changes anything.

**Comment by mckaygerhard** [comment]
ok meantime @oparoz make some test and made feedback u @lilarcor  please can u send and paste the logs and environment?

**Comment by hypery2k** [comment]
any changes or can we close the ticket?

**Comment by mckaygerhard** [comment]
i dont know @oparoz dont report any feedback, and in linux clinets the 8 series of oc (clinet and/or server) works very slow sometimes..

whit oc 7 or oc 6 i not have such issues in linux!

**Comment by oparoz** [comment]
I probably won't have time to test this before the oC conference.

**Comment by mckaygerhard** [comment]
umm so i'll close and if u have some problems reopen please, dont fill a new isue, reopne that if u have some problems related.
