### ISSUE TITLE
[oc8.1] Web interface does not respond after activating  storagecharts2 app 

### ISSUE THREAD

**Issue by cdamken** [hypery2k/owncloud#348]
#### Description:
After activating the storagecharts2 in ownCloud 8.1 the login over web-interface does not work anymore.
I could login over sync-client, android app, and one_not app.
I wanted to disable the app over occ, but the occ does not respond at all for any command:
 root@snoopy:/var/www/html/owncloud# sudo -u www-data php occ

root@snoopy:/var/www/html/owncloud# 

### Steps to reproduce
1. activate the storagechart app
2. login from another client: The page isn't redirecting properly
3. try to disable app. over occ -> Doesn't work anymore

Workaround: Remove the storagecharts2 directory and then works!

### Expected behaviour
Can login after I activate the app over the web-server

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS \n \l

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59

**Database:**
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          98563
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         5.5.44-MariaDB-1ubuntu0.14.04.1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 --------------

**PHP version:**
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.1 Community Edition

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - provisioning_api: 0.2
 - registration: 0.0.3
 - templateeditor: 0.1
 - updater: 0.6
 - bookmarks
 - contacts
 - delete_confirmation
 - direct_menu
 - external
 - files_antivirus
 - files_pdfviewer
 - ownnote
 - sharelinks
 - tasks
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxx',
    1 => 'xxxxx',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'ocxxxxxx',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'xxxxxx',
  'mail_domain' => 'xxxxxx',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxxxxx',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'xxxxxxx',
  'mail_smtppassword' => 'xxxxxx',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS = '/mnt/owncloud/data'

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Web server error log
No visible errors in access.log or error.log 

#### ownCloud log (data/owncloud.log)
This logs is when I was logged in and activated the app, After I try to login and there is no info about the app.
```
{"reqId":"Q7JiRsG+ssfjMx0gI6qw","remoteAddr":"IP.NUMMER","app":"PHP","message":"Undefined index: s at \/var\/www\/html\/owncloud\/apps\/storagecharts2\/ajax\/data.php#30","level":3,"time":"2015-07-30T09:50:02+00:00"}
{"reqId":"MJXmxZm4zZxjB+5XiZmk","remoteAddr":"IP.NUMMER","app":"PHP","message":"Undefined index: s at \/var\/www\/html\/owncloud\/apps\/storagecharts2\/ajax\/data.php#30","level":3,"time":"2015-07-30T09:51:09+00:00"}
{"reqId":"ASmUh1UYxYZCbUMujf+u","remoteAddr":"IP.NUMMER","app":"PHP","message":"Undefined index: s at \/var\/www\/html\/owncloud\/apps\/storagecharts2\/ajax\/data.php#30","level":3,"time":"2015-07-30T11:22:19+00:00"}
{"reqId":"\/MMgtkCcEnkqbr4hF0jk","remoteAddr":"IP.NUMMER","app":"PHP","message":"Undefined index: s at \/var\/www\/html\/owncloud\/apps\/storagecharts2\/ajax\/data.php#30","level":3,"time":"2015-07-30T16:14:04+00:00"}
```

**Comment by mckaygerhard** [comment]
thanks for the info provided.. will be very helpfull, there's a index problem in the storagehcarts2 that affect the ox 8.0.X release...

**Comment by cdamken** [comment]
@mckaygerhard this release is the 8.1.0, should I test it from the master?

**Comment by mckaygerhard** [comment]
yeah, please try and report feedback! BUT REMEMBER, u'r log said that seem the problem are the index .. but only if the problem are that i expected will be solved.. but if u'r log contains something more that u not paste here.. i think will be still in trouble!

**Comment by cdamken** [comment]
@mckaygerhard I test again and I come back with new logs if the  problem happens again :smile: Thanks a lot.

**Comment by mckaygerhard** [comment]
due u response, i assume resolved and close this issue. Please reopens if something related happened again.

**Comment by Worst45** [comment]
Hello, I still have the same problem on oc 8.1, even after using the last storagecharts2 github files:
 - occ command does not display anything
 - the login page loops while trying to fetch index.php

The error appears on a fresh install or after migrating from oc 8.0 to 8.1 (it worked on 8.0).

**Comment by mckaygerhard** [comment]
hello @Worst45 i ask to you to confirm: the oc give to u a redirection loop? please confirm quickly. seems related to the 351 redirection loop bug

**Comment by Worst45** [comment]
Yes, I confirm it loops if we try to access login page

tail -f /var/log/apache2/access.log
192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
...
192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)

(More than 20 times)

**Comment by mckaygerhard** [comment]
please, u are talking about another issue, please refers to issue 351 (i dont put the "#" before the number to dont link here)

**Comment by hypery2k** [comment]
can you please retry the latest nightly build? 

https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/

**Comment by Worst45** [comment]
I'm affraid it is not better... I took the storagecharts2_v2.6.2_build436.zip, and have still the same errors: occ empty, and http 302 loop on fetching index page.

Just before this 302 loop, I had the update page indicating that storagecharts2 was being updated. Just after the process, it redirect to index page, and then hangs.

**Comment by mckaygerhard** [comment]
@hypery2k the function in thisproblem are private in OC api, so i think must change between oc 8.0.X and 8.1.X, see #351 please

**Comment by cdamken** [comment]
@hypery2k  I found when the server crash..

1.- Enable the app
2.- Select: "Enable only for specific groups" and just add the admins.
3.- Logout and and try to log from another session

**Comment by mckaygerhard** [comment]
hi @cdamken do u have the solution? the oc-apps are not mantained any more, so until oc 7.X works, oc 8.X does not supported officially too many changes in oc api to track to a simple man...

if u have dissagree with this, rec laim to oc entrerprices that changes everyting in each version or better collaborate with working code solution to the problems
