### ISSUE TITLE
OC 8.0.4 Doesn't work

### ISSUE THREAD

**Issue by chr0m3** [hypery2k/owncloud#349]
If I install StorageCharts2 on ownCloud 8.0.4, It makes internal error.
Can't do anything even removing StorageCharts2.

Added : 
Oh I found how to remove - Remove storagecharts2 data from oc_appconfig table.

**Comment by mckaygerhard** [comment]
u must paste the debug log here, and also the setup environment! u make a invalid and non-sense issue.
