### ISSUE TITLE
connect to remote imap server

### ISSUE THREAD

**Issue by piecam** [hypery2k/owncloud#355]
HI,

I have my owncloud server at 192.168.150.253 with a URL https://cloud.test.com. I have another email server at 192.168.150.254 with IMAP/SMTP/HTTS.

How to setup in both Admin portal and user portal to have users in Owncloud to use Roundcube pluginto access this email.

Another question, is Roundcube having its own Address book, instead of using Ownlcoud addressbook?

thanks

**Comment by mckaygerhard** [comment]
please use the wiki, the issue are only for repòrt bugs.. not to ask for "how to"

the documentation are in: https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage please read carefully

**Comment by piecam** [comment]
Hi mckay,

sorry, I am a lit lost on that guide. If you can provide me a simple one with my specifics, it would much appreciated!

I currently use owncloud/mail, but I can not change password and create folders with it. I hope Roundcupe can help me on this.

thanks
peng

**Comment by mckaygerhard** [comment]
umm i quite not understand what du u want!

in the oc/rc interface integration if u disables the header links u could not have access to the configuration interface of the roundube..

and by other way, if u dont have right configured the mail linux server u don able to make directories/boxes (not folders ok ther's not such thing, wea re not in mocosoft world)

so its recommended se the mail service configuration..

by other way the guide of the plugin has examples and images of examples of configuration.. i recomende to read more around mail service and roundcube configuration
