### ISSUE TITLE
Roundcube: Cannot set different internal and external Roundcube server addresses

### ISSUE THREAD

**Issue by alexander255** [hypery2k/owncloud#357]
Currently one cannot, as far as I can tell, set a different address for *OwnCloud → RoundCube* and *User → RoundCube* communication. This can be a problem if your server is behind a reverse proxy.

My current workaround is to add this to `lib/RoundCubeLogin.class.php`/`sendRequest`:

    $url = "http://localhost:80/{$sep}{$path}";

before

    $responsObj = $this->openUrlConnection($url, $method, $postData);

and not change any RoundCuber server settings on the actual settings page.
This is obviously a temporary hack, but it works for now. ;-)

Will the RoundCube plugin support these kinds of scenarios. Should I code a proper settings page entry + setting + `sendRequest` patch?

**Comment by mckaygerhard** [comment]
roundcube plugin for owncloud are staled in developer terms as the original author and mantainer mention.

of course the openurl assume the hostname and all the rest are parsed in the postData parameter, so u'r case are very special as mention

i only help in code when i have some time or i can made something as far i  can doit.. currently  only mark and organize the issues so the project not fall in a hell of unforgiven sucess

if u can improve the code and make a pull request, are wellcome

in the help wiki, theres a how to implement a similar scenario, please revise the wiki also

**Comment by alexander255** [comment]
I made a pull request for a generic version of the fix I mentioned above.
Please tell me which page of the wiki I'm supposed to look at, I cannot find anything similar mentioned there…

**Comment by mckaygerhard** [comment]
umm maybe in 'Roundcube-OC-Installation-and-usage#subdomain-troubles' (subdomain-troubles section https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#subdomain-troubles) or i think we have to enhanced the wiki in that section!

if the section must be enhanced we must wait until someone can testit or i test it in one week
