### ISSUE TITLE
Storage Chart shows LDAP ID instead of fullname or loginname

### ISSUE THREAD

**Issue by Levanth** [hypery2k/owncloud#359]
When I use storagecharts2 with the LDAP Backend it shows the long id instead of "User Name" or "loginname" for the Charts

**Comment by Levanth** [comment]
can be closed, I am sorry, it was a misconfiguration in the LDAP Backend which led to this error

**Comment by mckaygerhard** [comment]
@Levanth can post here now closed what misconfiguration raise so other users when google-it can find and then solve it by own
