### ISSUE TITLE
Encryption failed. Public key not found for user@gmail.com

### ISSUE THREAD

**Issue by Hostile** [hypery2k/owncloud#360]
Hi, not an issu just question

It signing PGP, but i cant crypt it

How to crypt it ?

I get Encryption failed. Public key not found for user@email

**Comment by mckaygerhard** [comment]
i dont understand why u ask here, seem this its a question to rouncube specific app! not of plugin ap or oc app.. 

unless u are more specific, this issue are off-topic and must be closed!
