### ISSUE TITLE
Works with ownCloud 8.2 ?

### ISSUE THREAD

**Issue by jcharaoui** [hypery2k/owncloud#361]
Is the Roundcube plugin compatible with ownCloud 8.2?

**Comment by mckaygerhard** [comment]
dues the current status ot the rpoject, must suppost to NO:

**oc development becomes too unstable, has changes in every new version** and main developer of rc plugin let the development ... becose that many people including me comes angry!

if u have skills to make it! made pull request, but dont forget that must mantain compatibility with oc 6, oc 7 primary!

**Comment by hypery2k** [comment]
I've added an test setup for OC 8.2 but didn't try it for myself

**Comment by hypery2k** [comment]
Seems to work with OC8.2

**Comment by LukasReschke** [comment]
> oc development becomes too unstable, has changes in every new version and main developer of rc plugin let the development ... becose that many people including me comes angry!

That again is as well pure misinformation. ownCloud has a public (`OCP\`) and a private API (`OC\`, `OC_`) , the public API is promised to be stable for 3 years after a functionality has been deprecated.

In this case the application uses several private APIs where is no guarantee given about stability of these.

Cheers,
Lukas from @ownCloud

**Comment by hypery2k** [comment]
I don't want to blame anybody from the OC team. It's just that many people think of free OC apps as free beer. They expect a full service for no charge. That's the main reason of quitting. I've tried to move to Public APIs. It's just to hard for no money. It takes too much team and I have a real job ;)

**Comment by RealRancor** [comment]
@hypery2k I think that wasn't redirected to you but more to the quoted part about the misinformation spread by that guy.
