### ISSUE TITLE
User ID / Name for Storage Charts 2 v2.6.1  

### ISSUE THREAD

**Issue by clafargue** [hypery2k/owncloud#363]
Hello,

Could we use "displayname" instead of user UID ?
When LDAP user related, it is impossible to recognize easily the user displayed on the charts.

For example, '3A56F08A-DB81-4A0B-ADDD-BEAC010EB136' is displayed

Thanks

Christophe

OC=8.2

**Comment by mckaygerhard** [comment]
umm i think lasted git made this available yet: see #318 and seem u must use 8.0 as max version...

i will eventually support this app soon, but i do not support recent versions of OC due i hate the fashioned versioned changes adn everi have lasted of all thing! if i have something and its works well, not be necesary to change!

**Comment by mckaygerhard** [comment]
version 2.6.2 must work, reopen this if not.

**Comment by clafargue** [comment]
Hello,

Works correctly with names now

Thanks for support !

Cordialement, Best regards,
 
Christophe LAFARGUE





De :    PICCORO Lenz McKAY <notifications@github.com>
A :     hypery2k/owncloud <owncloud@noreply.github.com>
Cc :    clafargue <christophe_lafargue@fujifilm.eu>
Date :  22/01/2016 17:58
Objet : Re: [owncloud] User ID / Name for Storage Charts 2 v2.6.1   (#363)



version 2.6.2 must work, reopen this if not.
—
Reply to this email directly or view it on GitHub.


**********************************************************
Ce message et les documents qui y sont liés sont destinés exclusivement à 
leur(s) destinataire(s) et peuvent contenir des informations 
confidentielles. Si vous n'êtes pas destinés à recevoir ce message, merci 
d'en informer l'expéditeur par téléphone ou email et de détruire le 
présent message et les pièces qui y sont jointes. Si vous n'êtes pas le 
destinataire de ce message, vous n'êtes pas autorisés à copier le message 
et ses pièces jointes ni à en diffuser le contenu auprès de tierces 
personnes.
**********************************************************
This message and any attachment are only for the use of the intended 
recipient(s) and may contain confidential and/or privileged information. 
If you are not the intended recipient, please telephone or email the 
sender and delete this message and any attachment from your system. If you 
are not the intended recipient you must not copy this message or 
attachment or disclose the contents to any other person.
**********************************************************

**Comment by mckaygerhard** [comment]
hey @clafargue takes in consideration that development and maybe support of this app are staled by now.. 

and supported versions of OC are only 5 to 7.99 the 8.0 and 8.1 are only partially supported and there's no manpower collaboration ...

i take in consideration study the oc api, some of php 5, and take some code in this, but only due i use oc 7 and only need support this!
