### ISSUE TITLE
Class 'OC_Request' not found

### ISSUE THREAD

**Issue by royalterra** [hypery2k/owncloud#365]
Roundcube  Version 2 
Class 'OC_Request' not found in /var/www/cloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php on line 62

can any one tell me why I got this error and a blank page
Thanks

**Comment by mckaygerhard** [comment]
please report the complete detail of u'r setup server env and client so.. i mean versions, software, server, etc etc and step to reproduce errors.. also a "clean" log file, i mean a log only starting from steps only..

**Comment by hypery2k** [comment]
there's no Roundcube version 2 and no update on your current setup
