### ISSUE TITLE
App doesn't show up & credentials removed on logout.

### ISSUE THREAD

**Issue by kierenperry** [hypery2k/owncloud#367]
After configuring the app and launching it, a blank display appears. Log reveals nothing. Additionally, when logging out of and into Owncloud again, credentials dissapear. 

> Debug	roundcube	OC_RoundCube_AuthHelper.class.php->refresh(): Finished refresh for roundcube	2016-04-30T19:13:58+00:00
> Info	roundcube	OC_RoundCube_App.class.php->refresh(): Successfully refreshed the RC session.	2016-04-30T19:13:58+00:00
> Debug	roundcube	RoundcubeLogin.class.php: updateLoginStatus: \n Detected that we're logged in.	2016-04-30T19:13:58+00:00
> Debug	roundcube	RoundcubeLogin.class.php: updateLoginStatus: \n Detected that we're logged in.	2016-04-30T19:13:58+00:00
> Debug	roundcube	RoundcubeLogin.class.php: sendRequest: \n Got the following token: 1	2016-04-30T19:13:58+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n Got the following HTTP Status Code: (200)	2016-04-30T19:13:58+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n Disabling SSL verification.	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n cookie: roundcube_sessid=7b6c5705437ed73c0255fc338bb506f9;roundcube_sessauth=Sd465e162129f69c6ffea04a94d3122d9aa85bb72;	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n method: GET	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n url: https://plymouthrag.com/wm/	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: sendRequest: \n Trying to connect via "GET" to URL "https://plymouthrag.com/wm/" on host"plymouthrag.com"	2016-04-30T19:13:57+00:00
> Debug	roundcube	OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under /wm/	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: pre_construct: \n disableSSLverify: on	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: pre_construct: \n enableDebug: on	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcPath: /wm/	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcPort:	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcHost: plymouthrag.com	2016-04-30T19:13:57+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n Created new RoundCubeLogin instance:	2016-04-30T19:13:57+00:00
> Debug	roundcube	OC_RoundCube_AuthHelper.class.php->refresh(): Preparing refresh for roundcube	2016-04-30T19:13:57+00:00
> Debug	roundcube	OC_RoundCube_AuthHelper.class.php->refresh(): Finished refresh for roundcube	2016-04-30T19:13:28+00:00
> Info	roundcube	OC_RoundCube_App.class.php->refresh(): Successfully refreshed the RC session.	2016-04-30T19:13:28+00:00
> Debug	roundcube	RoundcubeLogin.class.php: updateLoginStatus: \n Detected that we're logged in.	2016-04-30T19:13:28+00:00
> Debug	roundcube	RoundcubeLogin.class.php: sendRequest: \n Got the following token: 1	2016-04-30T19:13:28+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n Got the following HTTP Status Code: (200)	2016-04-30T19:13:28+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n Disabling SSL verification.	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n cookie: roundcube_sessid=7b6c5705437ed73c0255fc338bb506f9;roundcube_sessauth=Sd465e162129f69c6ffea04a94d3122d9aa85bb72;	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n method: GET	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: openUrlConnection: \n url: https://plymouthrag.com/wm/	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: sendRequest: \n Trying to connect via "GET" to URL "https://plymouthrag.com/wm/" on host"plymouthrag.com"	2016-04-30T19:13:27+00:00
> Debug	roundcube	OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under /wm/	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: pre_construct: \n disableSSLverify: on	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: pre_construct: \n enableDebug: on	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcPath: /wm/	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcPort:	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n rcHost: plymouthrag.com	2016-04-30T19:13:27+00:00
> Debug	roundcube	RoundcubeLogin.class.php: post_construct: \n Created new RoundCubeLogin instance:	2016-04-30T19:13:27+00:00
> Debug	roundcube	OC_RoundCube_AuthHelper.class.php->refresh(): Preparing refresh for roundcube	2016-04-30T19:13:27+00:00
> 

![ocrc](https://cloud.githubusercontent.com/assets/18755019/14938044/f9222950-0f0f-11e6-8ed8-651c75050568.png)

**Comment by mckaygerhard** [comment]
1) rc plugin only works for OC << 8
2) rc plugin its in staled state
3) when posted a error/bug u must details version, env, etc of u'r setup

try manual login, automatic login credentials have a problem..
