### ISSUE TITLE
fixed login for oc 9, and a good plugin, bad that the development is discontinued

### ISSUE THREAD

**Issue by shwarz13** [hypery2k/owncloud#368]
v2.6.2 
- in ownclod v8.2.3 without changes works for me
- in ownclod v9.0.2 there was a mistake at preservation of email and the password ("Not submitted for us.")

I have corrected in roundcube/js/userSettings.js
was
`    if (password != '' && user != '') {`
`      $('#rc_usermail_update_message').show();`
`      // Serialize the data`
`      var post = $("#roundcube").serialize();`

became
`    if (password != '' && user != '') {`
`      $('#rc_usermail_update_message').show();`
`      // Serialize the data`
     **`var post = $("form#roundcube").serialize();`**

now works
can to whom will help

**Comment by mckaygerhard** [comment]
do u test autologin (no manual login), works with autologin on oc 8 and oc 9?

umm i can commit u'r changes.. let me test in oc 7 due i use 7 as priority

**Comment by shwarz13** [comment]
I have checked in os8.2.3 and os9.0.2, autologin works.
I can't test in os7. 
commit on your discretion.   

PS
I made changes to the appinfo/info.xml file

`        <dependencies> ` 
`          <owncloud min-version="5" max-version="`**9.0.2**`"/>` 
`        </dependencies>`

**Comment by mckaygerhard** [comment]
ok, let me wait if @hypery2k said something, if not i'll commit!

i quickly tested with rc 1.1.3 (no plugins configured) and oc 8.X (only standar apps enabled) and seems works, i not tested agains rc 1.2 or oc 9 due lazy je je

**Comment by hypery2k** [comment]
currently the tests are running, let's see: https://martinreinhardt-online.de/jenkins/view/BMP_OwnCloud/

**Comment by mckaygerhard** [comment]
@shwarz13 said that autologin are working! if are working for me at my production site i{ll suggest closes the bugs of the autologin when confirmed!

if the test running at the end report sucessfully (including oc 7 remenber) this issue can be close!

**Comment by hypery2k** [comment]
the automated tests seems to work. So I will publish a new last version of the roundcube app later

**Comment by mckaygerhard** [comment]
that's good news, please, can u waith i posted in the next 32 hours, i'm not at home and tomorrow i'll see how works in production server and report feedback here

this its the most wanted plugin in the oc app store, its glad to see something good its happened, thanks @shwarz13 for the patch and @hypery2k for made this great plugin

**Comment by hypery2k** [comment]
@mckaygerhard did it work for you?

**Comment by mckaygerhard** [comment]
ups, ok sorry for late! i'll close now due i cannot test for now, i'm very busy at my work!

in the next week i'll test the plugin and if work then report feedback here or not!

PD: currently in production have a modified version of the kolab owncloud integration.. i wish to detect where and when the oc are login from that plugin to disable the rc-app and both can cohexist

**Comment by hypery2k** [comment]
@mckaygerhard Did work out for you?

**Comment by mckaygerhard** [comment]
hey, I had forgotten! It is that really I am very busy but I'm trying it RIGHT NOW! 

WELLL LIKE A CHARM!!!! arrggg !!!! this now closed and confirmed!

i not tested deeply but works ! oh men i so happy!

thanks for our effors @hypery2k and @shwarz13 now its working in owncloud 7, owncloud 8 and lasted!

**Comment by hypery2k** [comment]
I'm currently trying to get a build up and running. Hopefully I will publish a new version?

**Comment by hypery2k** [comment]
new version is released: http://apps.owncloud.com/content/show.php?content=151523

**Comment by mckaygerhard** [comment]
great, new version its need, sorry for delay, i'm very busy with a other plugin that integrates in inverse way, oc into rc interface!
