### ISSUE TITLE
A regex in RoundCubeLogin.class seems to be outdated

### ISSUE THREAD

**Issue by LeonardoRM** [hypery2k/owncloud#369]
roundcubemail-0.9.5
ownCloud 9.0.0
OC app: RoundCube Mail 2.6.1
Autologin enabled

The errors I first saw are these:

```
Error   roundcube   OC_RoundCube_App.class.php->showMailFrame(): There were login errors
Error   roundcube   OC_RoundCube_App.class.php->showMailFrame(): Autologin is enabled. Seems that the owncloud and roundcube login details do not match
Error   roundcube   OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube
Error   roundcube   Not rendering roundcube iframe view due to errors
Error   roundcube   Got the following error code: 11
```

After debugging I realized that the problem might be in a regular expression that is not matching due to a simple comma ','. I removed it and some errors related to this stopped. There are some `addDebug` calls in the functions I provide next, that helped track the _extra comma_.

The file is `lib/RoundCubeLogin.class.php` and the regex is in two functions:
`private function updateLoginStatus($forceUpdate = false)` and
`private function sendRequest($path, $postData = false)`

Both lines 343 and 442 contain the regex:
`if (preg_match('/"request_token":"([^"]+)",/mi', $response, $m)) {`

and tyeh should be like this, without the comma ',' before the end of the regex:
`if (preg_match('/"request_token":"([^"]+)"/mi', $response, $m)) {`

The interesting portion of the `$response` string looks like this:
"contentframe":"messagecontframe",**"request_token":"55df9787e1693f1f0665b9e96b488434"**});

Note that the _not currently matched_ string is the last of an array, so there is no comma.

After this change, it got a bit better in my environment.

Can anyone else confirm this?
##

**Comment by mckaygerhard** [comment]
i think the comma is added due most parts of and set of array.. since lasted commit that able to work with oc 9.X also works with oc 7

do u test it in others enviroments?

we need to test in others enviroment! please some one can test also (i can do it but not right now, in few weeks)

**Comment by LeonardoRM** [comment]
> do u test it in others enviroments?

I only have a production env :/

**Comment by mckaygerhard** [comment]
so then, need to test in others enviroment! please some one can test also (i can do it but not right now, in few weeks), and thanks for the report

**Comment by mckaygerhard** [comment]
sorry for the late, the next week iĺl free of some task and test this ! i see that the request not currently matched string is the last of an array, so must not thereś a comma here.. in teory

**Comment by mckaygerhard** [comment]
big outdate and busy, i'll test this in oc 9 and oc 7 in these days, sorry for late

**Comment by mckaygerhard** [comment]
i installed the path and i can confirm the log "Unknow parameter ','" in the log files where gone when i use the patch.. 

but now i get the following error: `Undefined index: defaultValue at /home/intranet/elfichero/core/ajax/appconfig.php#29` insteresting also that in oc 7.0.12.2 works and in 7.0.15.2 does not work anymore the roundcube login

so i cannot determine if this patch are working or not! due the new log entry, if u can confirm or somebody that whit "," removed does not cause errors in oc 7 and oc 6 good by me!

**Comment by mckaygerhard** [comment]
umm its worked.. this patch must be integrated, my problem was a cache proxy reverse problem, the rare log its a core defect.. when enabled manually a plugin app, i'll integrate this in few hours
