### ISSUE TITLE
storagechart2 on owncloud 9 is compatible

### ISSUE THREAD

**Issue by undigo** [hypery2k/owncloud#370]
Hi,
To share with most people, I try to find a compatible Storage Charts for control usage for my users on the last Owncloud 9.0.1 Bitnami stack installation (with 1an1 Apps Cloud hosting)

Step to reproduce :
1. I use  the owncloud/storagecharts2/src/main/php folder then rename the php folder to storagecharts2
2. I try to activate the apps from Owncloud with UI but I've got  : 

`Class 'OC_Config' not found at /opt/bitnami/apps/owncloud/htdocs/apps/storagecharts2/appinfo/app.php#54`
3. I use the same method that [https://github.com/fcturner/passwords/issues/135](https://github.com/fcturner/passwords/issues/135) to correct the OC_Config class not found (from perhaps this nine Owncloud version refactoring ?)
4.  in file apps/storagecharts2/appinfo/app.php I change this : 
`$datadir = OC_Config::getValue('datadirectory') .'/'.OCP\User::getUser();`
by this : 
`
$config = \OC::$server->getConfig();
$datadir = $config->getSystemValue('datadirectory') .'/'.OCP\User::getUser();
`
1. activate the Owncloud Apps and show must go on :)
   ![image 1008](https://cloud.githubusercontent.com/assets/1070969/18610144/adbb8146-7d14-11e6-9510-1c209c2527c7.jpg)

Is it a security risk for O9 ? 
##

**Comment by mckaygerhard** [comment]
yeah seems that are not problem, searching for the method at the oc documentation:
https://doc.owncloud.org/server/7.0/developer_manual/app/configuration.html

that change seems compatible with oc 7 and oc 8 so coverts oc from 7 to 9, but must be tested

iĺl have some time in few weeks, test that change and merge if works..

**Comment by TheBready** [comment]
Hey, Is a crazy CPU load after activation of the addon normal?

**Comment by mckaygerhard** [comment]
do you have also crazy cpu load @undigo ? if not its a misconfiguration on u'r env.. @TheBready

**Comment by vanthoi** [comment]
Thank you to have a guide. I have been to running it on OC 9.1.2
![image](https://cloud.githubusercontent.com/assets/13189483/21074564/9b35aed2-bf2e-11e6-8bc7-4c296502b7aa.png)

**Comment by mckaygerhard** [comment]
@vanthoi the plugin are working correctly? there's no cpu overload at page load?

**Comment by mckaygerhard** [comment]
i tested the patch and confirm that works!

about the cpu load, yeahp, for now, the plugin take some reads to make statics and build the chart, this are due many changes over the OC 6 vs OC 7/8 and now OC 9 changes of architecture respect the HighCharts javascripts, features and pulls request are wellcome

i'll pull that changes in few hours and close this, due the patch works in OC 7 throught OC 9.X

**Comment by mckaygerhard** [comment]
**NOTE about cpu load** INVALID ISSUE, i use postgresql in production and no cpu workload ! the problem its a poor database engine such as mysql, see :  https://github.com/owncloud/client/issues/331 and see https://github.com/owncloud/core/issues/21915

**Comment by pasnox** [comment]
Does not works with ownCloud 9.0.7 (stable).
Upon activation that produce Internal Server Error on the web server (Error 500).

**Comment by mckaygerhard** [comment]
reopen the issue when u can post the log (well formated) here . please can u paste the log of errors here (use a clean new log, without the garbage of others plugins)

**Comment by vanthoi** [comment]
I confirm that this fix works from OC 9.1.2 to the current version OC 9.1.5
You can install and comments :)
![image](https://cloud.githubusercontent.com/assets/13189483/26192062/71847a22-3bda-11e7-96df-0f0b5afccd3d.png)

**Comment by mckaygerhard** [comment]
of course works,. i noted many stupid mistakes and lot of problems when using the poor mysql/mariadb engine, the owncloud software get crazy and ilogic in nomadays, the fork nextcloud seems now similar, many updates "update update" but no stability...

i use only OC 7.0.6 and works better and faster, i'll not update any OC installation anymore ! currently i only commit patches usefully for OC 7 in this repo unless anyone have for others versions
