### ISSUE TITLE
preview pane issues when using hardened apache ssl settings

### ISSUE THREAD

**Issue by aw1604** [hypery2k/owncloud#371]
Hello,

I just applied a set of recommended apache ssl settings (https://cipherli.st) and noticed that the preview pane stopped working. I was able to track this down to this two config lines in ssl.conf - when enabled, all ajax stuff (preview pane, but more painful also the settings) stops working. 

# from Cipherli.st
### Header always set X-Content-Type-Options nosniff

Can anybody please try to reproduce / test this issue ?

Best Rgds,
aw1604

**Comment by mckaygerhard** [comment]
err i think u have in wrong git repo, maybe u must refers to https://github.com/owncloud/core/issues
