### ISSUE TITLE
Clarify Bountysource salt funding campaign

### ISSUE THREAD

**Issue by tuxayo** [hypery2k/owncloud#372]
https://salt.bountysource.com/teams/hypery2k-owncloud

It's just called ownCloud which make it sound like it's the official ownCloud donation page.

Which conflict with the real one: https://salt.bountysource.com/teams/owncloud

**Comment by mckaygerhard** [comment]
no worry, but well there's one important difference: one of the page has only one member, the other many, so also dont open issues to make new comments! cheers

**Comment by tuxayo** [comment]
Ok, sorry by which channel should one contact you for these kind of topics?

**Comment by mckaygerhard** [comment]
well: this! but i closed due the url are different, and amount of members, also its a good cach to bounty.
