### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by tuxayo** [hypery2k/owncloud#373]
The readme says:

> I quit the development of OwnCloud apps Sorry to say, if anybody wants to take over the project, feel free to take over.

Is this still valid? As there are still commits and updates. Is the project in "maintenance mode"? (just doing what's necessary to keep the apps working)

**Comment by mckaygerhard** [comment]
yeah, project are stalled, manteniance mode are just for those commits that people contribute

feel free to contribute if u have any patches or solution to improve this great project!
