### ISSUE TITLE
ERROR Roundcube 1.2.3 && ownCloud 0.9.1

### ISSUE THREAD

**Issue by mario26** [hypery2k/owncloud#374]
Hello !

I use a new installation of Roundcube (1.2.3) and ownCloud (0.9.1), but I cannot use the Roundcube plugin.

Here is the full log log: Log file: https://upload.devosi.org/f.php?h=1nZ1BVOW

View error:
```
Error roundcube Got the following error code: 11 2017-01-16T02:04:04+00:00
Error roundcube Not rendering roundcube iframe view due to errors 2017-01-16T02:04:04+00:00
Error roundcube OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2017-01-16T02:04:04+00:00`
```
Can you help me ?

Thank you :)

**Comment by mckaygerhard** [comment]
hi, can u try the manual login, disable automatic login at admin settings and try again, post feedback here...

**Comment by mario26** [comment]
Hi !

Here is some additional information.

**Disabled autologin for users**
Screenshot  setting admin Roundcube plugin : https://upload.devosi.org/f.php?h=3N5lQu0R&p=1
Screenshot  setting personal Roundcube plugin : https://upload.devosi.org/f.php?h=1Q3inhP7&p=1
Screenshot  webmail Roundcube plugin : https://upload.devosi.org/f.php?h=37y0le-_&p=1
**Log :**
```
Error	roundcube	Found no valid public key for user mario (mail user: mail@domain.org)	2017-01-16T22:10:07+00:00
Error	roundcube	Got the following error code: 10	2017-01-16T22:09:34+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2017-01-16T22:09:34+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2017-01-16T22:09:34+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2017-01-16T22:09:34+00:00
Error	index	Exception: {"Exception":"Error","Message":"Class 'OC_Appconfig' not found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/owncloud\/lib\/private\/Route\/Route.php(154) : runtime-created function(1): require_once()\n#1 [internal function]: __lambda_func('rcRefreshInterv...')\n#2 \/var\/www\/owncloud\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func('\\x00lambda_24', Array)\n#3 \/var\/www\/owncloud\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/roundcube...')\n#4 \/var\/www\/owncloud\/owncloud\/index.php(54): OC::handleRequest()\n#5 {main}","File":"\/var\/www\/owncloud\/owncloud\/apps\/roundcube\/ajax\/adminSettings.php","Line":59}	2017-01-16T22:09:26+00:00
```
**Enable autologin for users**
Screenshot  setting admin Roundcube plugin : https://upload.devosi.org/f.php?h=0dr_2yEy&p=1
Screenshot  webmail Roundcube plugin : https://upload.devosi.org/f.php?h=2htRCbOD&p=1
**Log : No log out with this configuration :-/ **

The "Disable SSL verification, e.g. for self-signed certificates" parameter is blocked selected. I have the impression that there is a problem of dialogue with the database or that something is in conflict. I use MySql.

Thank you for your help.

**Comment by mckaygerhard** [comment]
noted hat u have a roundcube url in setup event the path from server root, u have a misconsfiguration, please read carefullky the instructions and repeat the setup

in other hands, if u have roundcube in a different domain, right, if that ist the case, u must use a reverse proxy trick, to emulates the local instalation of roundcube, please refers to the wiki documentation for install in right way

**Comment by mario26** [comment]
Oops! Sorry, I did not get the right setting, now it works. Thank you !
